import '../images/sprite-images/logo.svg'
// import '../images/sprite-images/papers.svg'
import '../images/sprite-images/clock.svg'
import '../images/sprite-images/star.svg'
import '../images/sprite-images/mail.svg'
import '../images/sprite-images/phone.svg'
// import '../images/sprite-images/play.svg'
// import '../images/sprite-images/arr-bottom.svg'
// import '../images/sprite-images/arr-right.svg'
